// Implementation file for parser generated by fsyacc
module PracticalAssignmentParser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 2 "PracticalAssignmentParser.fsp"

open PracticalAssignmentTypesAST

# 10 "PracticalAssignmentParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | SEMCOL
  | ASS
  | BRACK
  | EQ
  | NEQ
  | GT
  | GEQ
  | LT
  | LEQ
  | AND
  | OR
  | NOT
  | SCAND
  | SCOR
  | UMINUS
  | TIMES
  | DIV
  | PLUS
  | MINUS
  | POW
  | LPAR
  | RPAR
  | EOF
  | NAME of (string)
  | NUM of (float)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_SEMCOL
    | TOKEN_ASS
    | TOKEN_BRACK
    | TOKEN_EQ
    | TOKEN_NEQ
    | TOKEN_GT
    | TOKEN_GEQ
    | TOKEN_LT
    | TOKEN_LEQ
    | TOKEN_AND
    | TOKEN_OR
    | TOKEN_NOT
    | TOKEN_SCAND
    | TOKEN_SCOR
    | TOKEN_UMINUS
    | TOKEN_TIMES
    | TOKEN_DIV
    | TOKEN_PLUS
    | TOKEN_MINUS
    | TOKEN_POW
    | TOKEN_LPAR
    | TOKEN_RPAR
    | TOKEN_EOF
    | TOKEN_NAME
    | TOKEN_NUM
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_expression

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | SEMCOL  -> 0 
  | ASS  -> 1 
  | BRACK  -> 2 
  | EQ  -> 3 
  | NEQ  -> 4 
  | GT  -> 5 
  | GEQ  -> 6 
  | LT  -> 7 
  | LEQ  -> 8 
  | AND  -> 9 
  | OR  -> 10 
  | NOT  -> 11 
  | SCAND  -> 12 
  | SCOR  -> 13 
  | UMINUS  -> 14 
  | TIMES  -> 15 
  | DIV  -> 16 
  | PLUS  -> 17 
  | MINUS  -> 18 
  | POW  -> 19 
  | LPAR  -> 20 
  | RPAR  -> 21 
  | EOF  -> 22 
  | NAME _ -> 23 
  | NUM _ -> 24 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_SEMCOL 
  | 1 -> TOKEN_ASS 
  | 2 -> TOKEN_BRACK 
  | 3 -> TOKEN_EQ 
  | 4 -> TOKEN_NEQ 
  | 5 -> TOKEN_GT 
  | 6 -> TOKEN_GEQ 
  | 7 -> TOKEN_LT 
  | 8 -> TOKEN_LEQ 
  | 9 -> TOKEN_AND 
  | 10 -> TOKEN_OR 
  | 11 -> TOKEN_NOT 
  | 12 -> TOKEN_SCAND 
  | 13 -> TOKEN_SCOR 
  | 14 -> TOKEN_UMINUS 
  | 15 -> TOKEN_TIMES 
  | 16 -> TOKEN_DIV 
  | 17 -> TOKEN_PLUS 
  | 18 -> TOKEN_MINUS 
  | 19 -> TOKEN_POW 
  | 20 -> TOKEN_LPAR 
  | 21 -> TOKEN_RPAR 
  | 22 -> TOKEN_EOF 
  | 23 -> TOKEN_NAME 
  | 24 -> TOKEN_NUM 
  | 27 -> TOKEN_end_of_input
  | 25 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_expression 
    | 3 -> NONTERM_expression 
    | 4 -> NONTERM_expression 
    | 5 -> NONTERM_expression 
    | 6 -> NONTERM_expression 
    | 7 -> NONTERM_expression 
    | 8 -> NONTERM_expression 
    | 9 -> NONTERM_expression 
    | 10 -> NONTERM_expression 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 27 
let _fsyacc_tagOfErrorTerminal = 25

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | SEMCOL  -> "SEMCOL" 
  | ASS  -> "ASS" 
  | BRACK  -> "BRACK" 
  | EQ  -> "EQ" 
  | NEQ  -> "NEQ" 
  | GT  -> "GT" 
  | GEQ  -> "GEQ" 
  | LT  -> "LT" 
  | LEQ  -> "LEQ" 
  | AND  -> "AND" 
  | OR  -> "OR" 
  | NOT  -> "NOT" 
  | SCAND  -> "SCAND" 
  | SCOR  -> "SCOR" 
  | UMINUS  -> "UMINUS" 
  | TIMES  -> "TIMES" 
  | DIV  -> "DIV" 
  | PLUS  -> "PLUS" 
  | MINUS  -> "MINUS" 
  | POW  -> "POW" 
  | LPAR  -> "LPAR" 
  | RPAR  -> "RPAR" 
  | EOF  -> "EOF" 
  | NAME _ -> "NAME" 
  | NUM _ -> "NUM" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | SEMCOL  -> (null : System.Object) 
  | ASS  -> (null : System.Object) 
  | BRACK  -> (null : System.Object) 
  | EQ  -> (null : System.Object) 
  | NEQ  -> (null : System.Object) 
  | GT  -> (null : System.Object) 
  | GEQ  -> (null : System.Object) 
  | LT  -> (null : System.Object) 
  | LEQ  -> (null : System.Object) 
  | AND  -> (null : System.Object) 
  | OR  -> (null : System.Object) 
  | NOT  -> (null : System.Object) 
  | SCAND  -> (null : System.Object) 
  | SCOR  -> (null : System.Object) 
  | UMINUS  -> (null : System.Object) 
  | TIMES  -> (null : System.Object) 
  | DIV  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | MINUS  -> (null : System.Object) 
  | POW  -> (null : System.Object) 
  | LPAR  -> (null : System.Object) 
  | RPAR  -> (null : System.Object) 
  | EOF  -> (null : System.Object) 
  | NAME _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | NUM _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 9us; 65535us; 0us; 2us; 12us; 4us; 13us; 5us; 14us; 6us; 15us; 7us; 16us; 8us; 17us; 9us; 18us; 10us; 20us; 11us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 6us; 1us; 2us; 3us; 4us; 5us; 6us; 1us; 1us; 6us; 2us; 2us; 3us; 4us; 5us; 6us; 6us; 2us; 3us; 3us; 4us; 5us; 6us; 6us; 2us; 3us; 4us; 4us; 5us; 6us; 6us; 2us; 3us; 4us; 5us; 5us; 6us; 6us; 2us; 3us; 4us; 5us; 6us; 6us; 6us; 2us; 3us; 4us; 5us; 6us; 7us; 6us; 2us; 3us; 4us; 5us; 6us; 8us; 6us; 2us; 3us; 4us; 5us; 6us; 10us; 1us; 2us; 1us; 3us; 1us; 4us; 1us; 5us; 1us; 6us; 1us; 7us; 1us; 8us; 1us; 9us; 1us; 10us; 1us; 10us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 11us; 13us; 20us; 27us; 34us; 41us; 48us; 55us; 62us; 69us; 71us; 73us; 75us; 77us; 79us; 81us; 83us; 85us; 87us; |]
let _fsyacc_action_rows = 22
let _fsyacc_actionTableElements = [|4us; 32768us; 17us; 17us; 18us; 18us; 20us; 20us; 24us; 19us; 0us; 49152us; 6us; 32768us; 15us; 12us; 16us; 13us; 17us; 14us; 18us; 15us; 19us; 16us; 22us; 3us; 0us; 16385us; 1us; 16386us; 19us; 16us; 1us; 16387us; 19us; 16us; 3us; 16388us; 15us; 12us; 16us; 13us; 19us; 16us; 3us; 16389us; 15us; 12us; 16us; 13us; 19us; 16us; 1us; 16390us; 19us; 16us; 3us; 16391us; 15us; 12us; 16us; 13us; 19us; 16us; 3us; 16392us; 15us; 12us; 16us; 13us; 19us; 16us; 6us; 32768us; 15us; 12us; 16us; 13us; 17us; 14us; 18us; 15us; 19us; 16us; 21us; 21us; 4us; 32768us; 17us; 17us; 18us; 18us; 20us; 20us; 24us; 19us; 4us; 32768us; 17us; 17us; 18us; 18us; 20us; 20us; 24us; 19us; 4us; 32768us; 17us; 17us; 18us; 18us; 20us; 20us; 24us; 19us; 4us; 32768us; 17us; 17us; 18us; 18us; 20us; 20us; 24us; 19us; 4us; 32768us; 17us; 17us; 18us; 18us; 20us; 20us; 24us; 19us; 4us; 32768us; 17us; 17us; 18us; 18us; 20us; 20us; 24us; 19us; 4us; 32768us; 17us; 17us; 18us; 18us; 20us; 20us; 24us; 19us; 0us; 16393us; 4us; 32768us; 17us; 17us; 18us; 18us; 20us; 20us; 24us; 19us; 0us; 16394us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 5us; 6us; 13us; 14us; 16us; 18us; 22us; 26us; 28us; 32us; 36us; 43us; 48us; 53us; 58us; 63us; 68us; 73us; 78us; 79us; 84us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 2us; 3us; 3us; 3us; 3us; 3us; 2us; 2us; 1us; 3us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16385us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16393us; 65535us; 16394us; |]
let _fsyacc_reductions ()  =    [| 
# 221 "PracticalAssignmentParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 230 "PracticalAssignmentParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 42 "PracticalAssignmentParser.fsp"
                                                         _1 
                   )
# 42 "PracticalAssignmentParser.fsp"
                 : expr));
# 241 "PracticalAssignmentParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 52 "PracticalAssignmentParser.fsp"
                                                         TimesExpr(_1,_3) 
                   )
# 52 "PracticalAssignmentParser.fsp"
                 : expr));
# 253 "PracticalAssignmentParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 53 "PracticalAssignmentParser.fsp"
                                                         DivExpr(_1,_3) 
                   )
# 53 "PracticalAssignmentParser.fsp"
                 : expr));
# 265 "PracticalAssignmentParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 54 "PracticalAssignmentParser.fsp"
                                                         PlusExpr(_1,_3) 
                   )
# 54 "PracticalAssignmentParser.fsp"
                 : expr));
# 277 "PracticalAssignmentParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 55 "PracticalAssignmentParser.fsp"
                                                         MinusExpr(_1,_3) 
                   )
# 55 "PracticalAssignmentParser.fsp"
                 : expr));
# 289 "PracticalAssignmentParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 56 "PracticalAssignmentParser.fsp"
                                                         PowExpr(_1,_3) 
                   )
# 56 "PracticalAssignmentParser.fsp"
                 : expr));
# 301 "PracticalAssignmentParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 57 "PracticalAssignmentParser.fsp"
                                                         UPlusExpr(_2) 
                   )
# 57 "PracticalAssignmentParser.fsp"
                 : expr));
# 312 "PracticalAssignmentParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 58 "PracticalAssignmentParser.fsp"
                                                         UMinusExpr(_2) 
                   )
# 58 "PracticalAssignmentParser.fsp"
                 : expr));
# 323 "PracticalAssignmentParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : float)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 59 "PracticalAssignmentParser.fsp"
                                                         Num(_1) 
                   )
# 59 "PracticalAssignmentParser.fsp"
                 : expr));
# 334 "PracticalAssignmentParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 60 "PracticalAssignmentParser.fsp"
                                                         _2 
                   )
# 60 "PracticalAssignmentParser.fsp"
                 : expr));
|]
# 346 "PracticalAssignmentParser.fs"
let tables () : FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 28;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : expr =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
